/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.formularios;

import aplicacion.Bicicleta;
import aplicacion.Estacion;
import aplicacion.FachadaAplicacion;
import gui.modelos.modeloListaBicicletas;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author imarc
 */
public class DiaBicis extends javax.swing.JDialog {

    Estacion estacionUsada;
    FachadaAplicacion fa;
    
    /**
     * Creates new form DiaBicis
     */
    public DiaBicis(JFrame parent, boolean modal, FachadaAplicacion fa, Estacion estacion)
    {
        super(parent, modal);
        this.fa = fa;
        this.estacionUsada = estacion;
        this.setLocationRelativeTo(null);
        initComponents();
        
        this.lblNombreEstacion.setText(estacion.ubicacion());
        
        this.listarBicicletas();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistBicisDisponibles = new javax.swing.JList<>();
        lblEstacion = new javax.swing.JLabel();
        lblNombreEstacion = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlistBicisDisponibles.setModel(new modeloListaBicicletas());
        jScrollPane1.setViewportView(jlistBicisDisponibles);

        lblEstacion.setText("Estacion:");

        lblNombreEstacion.setText("jLabel2");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanPanelPrincipalLayout = new javax.swing.GroupLayout(jpanPanelPrincipal);
        jpanPanelPrincipal.setLayout(jpanPanelPrincipalLayout);
        jpanPanelPrincipalLayout.setHorizontalGroup(
            jpanPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jpanPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblEstacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreEstacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        jpanPanelPrincipalLayout.setVerticalGroup(
            jpanPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstacion)
                    .addComponent(lblNombreEstacion))
                .addGap(18, 18, 18)
                .addGroup(jpanPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(jpanPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.listarBicicletas();
    }//GEN-LAST:event_btnActualizarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistBicisDisponibles;
    private javax.swing.JPanel jpanPanelPrincipal;
    private javax.swing.JLabel lblEstacion;
    private javax.swing.JLabel lblNombreEstacion;
    // End of variables declaration//GEN-END:variables

    private void listarBicicletas()
    {
        modeloListaBicicletas modelo                = (modeloListaBicicletas) this.jlistBicisDisponibles.getModel();
        List<Bicicleta>       bicicletasSinReservar = fa.obtenerBicisLibresPorEstacion(estacionUsada);
        modelo.setFilas(bicicletasSinReservar);

    }
}
