/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.formularios;

import aplicacion.Estacion;
import aplicacion.FachadaAplicacion;
import gui.modelos.modeloTablaEstaciones;

import java.text.MessageFormat;
import java.util.ResourceBundle;

/**
 *
 * @author imarc
 */
public class VPrincipalUsuario extends javax.swing.JFrame {

    FachadaAplicacion fa;
    ResourceBundle idioma;
    /**
     * Creates new form VPrincipalUsuario
     */
    public VPrincipalUsuario(FachadaAplicacion fa)
    {
        this.fa = fa;
        idioma = fa.pedirBundle();
        initComponents();
        this.gestionarBicicletaEnUso();
        this.listarEstaciones();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConfig = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        lblListaDeEstaciones = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnDevolverBici = new javax.swing.JButton();
        chkBiciEnUso = new javax.swing.JCheckBox();
        btnBicisEstacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstaciones = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnReservarBicicleta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConfig.setText(idioma.getString("configuracion"));
        btnConfig.setMaximumSize(new java.awt.Dimension(130, 28));
        btnConfig.setMinimumSize(new java.awt.Dimension(130, 28));
        btnConfig.setPreferredSize(new java.awt.Dimension(130, 28));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        btnPerfil.setText(idioma.getString("perfil"));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        lblListaDeEstaciones.setText(idioma.getString("lista.de.estaciones"));

        btnSalir.setText(idioma.getString("Salir"));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnDevolverBici.setText(idioma.getString("devolver.bicicleta"));
        btnDevolverBici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverBiciActionPerformed(evt);
            }
        });

        chkBiciEnUso.setText(idioma.getString("bicicleta.en.uso"));
        chkBiciEnUso.setEnabled(false);

        btnBicisEstacion.setText(idioma.getString("bicicletas"));
        btnBicisEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBicisEstacionActionPerformed(evt);
            }
        });

        tablaEstaciones.setModel(new modeloTablaEstaciones());
        jScrollPane2.setViewportView(tablaEstaciones);

        btnActualizar.setText(idioma.getString("actualizar"));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnReservarBicicleta.setText(idioma.getString("reservar"));
        btnReservarBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarBicicletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDevolverBici)
                                .addGap(113, 113, 113)
                                .addComponent(chkBiciEnUso)
                                .addGap(45, 45, 45))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBicisEstacion)
                    .addComponent(btnActualizar)
                    .addComponent(btnReservarBicicleta))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(lblListaDeEstaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfil))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReservarBicicleta)
                        .addGap(15, 15, 15)
                        .addComponent(btnBicisEstacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(lblListaDeEstaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDevolverBici)
                            .addComponent(chkBiciEnUso))
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBicisEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBicisEstacionActionPerformed
        // TODO add your handling code here:
        int index = tablaEstaciones.getSelectedRow();
        if (index != -1) {
            aplicacion.Estacion estacionSeleccionada = ((modeloTablaEstaciones) tablaEstaciones.getModel()).obtenerEstacion(index);
            DiaBicis menuBicis = new DiaBicis(this, true,this.fa, estacionSeleccionada);
            menuBicis.setVisible(true);
            menuBicis.pack();
            menuBicis.setLocationRelativeTo(null);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("debes.seleccionar.una.estacion"));
        }
    }//GEN-LAST:event_btnBicisEstacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        listarEstaciones();
        gestionarBicicletaEnUso();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDevolverBiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverBiciActionPerformed
        int filaSeleccionada = tablaEstaciones.getSelectedRow();
        if (filaSeleccionada != -1)
        {
            aplicacion.Estacion estacionSeleccionada = ((modeloTablaEstaciones) tablaEstaciones.getModel()).obtenerEstacion(filaSeleccionada);
            if(!fa.devolverBicicleta(estacionSeleccionada))
            {
                javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("el.aforo.de.la.estacion.no.es.suficiente.para.devolver.la.bicicleta"));
            }

            listarEstaciones();
            gestionarBicicletaEnUso();
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("debes.seleccionar.una.estacion"));
        }
    }//GEN-LAST:event_btnDevolverBiciActionPerformed

    private void btnReservarBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarBicicletaActionPerformed
        int filaSeleccionada = tablaEstaciones.getSelectedRow();
        if (filaSeleccionada != -1)
        {
            boolean usuarioTieneBici = fa.usuarioTieneBici();

            if(usuarioTieneBici)
            {
                javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("ya.tienes.una.bicicleta.reservada") +
                        idioma.getString("por.favor.devuelvela.antes.de.reservar.otra"));
                return;
            }

            Estacion estacionSeleccionada = ((modeloTablaEstaciones) tablaEstaciones.getModel()).obtenerEstacion(filaSeleccionada);
            int bicicleta_asignada = fa.reservarBicicleta(estacionSeleccionada);
            if (bicicleta_asignada == -1)
            {
                javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("no.hay.bicicletas.disponibles.en.esta.estacion"));
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this, MessageFormat.format(idioma.getString("bicicleta.numero.0.reservada"), bicicleta_asignada));
            }
            listarEstaciones();
            gestionarBicicletaEnUso();
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, idioma.getString("debes.seleccionar.una.estacion"));
        }
    }//GEN-LAST:event_btnReservarBicicletaActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // lanzo la interfaz de sel. de idioma
        VIdioma idioma = new VIdioma(this,true,this.fa);
        idioma.setLocationRelativeTo(null);
        idioma.pack();
        idioma.setVisible(true);

    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        DiaUsuario menuUsuario = new DiaUsuario(this, fa);
        menuUsuario.setLocationRelativeTo(null);
        menuUsuario.setVisible(true);

    }//GEN-LAST:event_btnPerfilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBicisEstacion;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnDevolverBici;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReservarBicicleta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkBiciEnUso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListaDeEstaciones;
    private javax.swing.JTable tablaEstaciones;
    // End of variables declaration//GEN-END:variables

    private void listarEstaciones()
    {
        modeloTablaEstaciones modelo = (modeloTablaEstaciones) tablaEstaciones.getModel();
        modelo.setFilas(fa.preguntaLasEstaciones(), fa.preguntaLasBicicletasPorEstacion());
    }

    private void gestionarBicicletaEnUso()
    {
        boolean usuarioTieneBici = fa.usuarioTieneBici();
        if (usuarioTieneBici)
        {
            btnDevolverBici.setEnabled(true);
            chkBiciEnUso.setSelected(true);
//            chkBiciEnUso.set


        }
        else
        {
            chkBiciEnUso.setSelected(false);
            btnDevolverBici.setEnabled(false);
        }
    }

}
