insert into estacion (ubicacion, aforo) values ('8001 VILLA PARK DRIVE', 1);
insert into estacion (ubicacion, aforo) values ('86 boulevard Haussmann', 2);
insert into estacion (ubicacion, aforo) values ('1008 OAK STREET', 3);
insert into estacion (ubicacion, aforo) values ('P.O. BOX 406', 4);
insert into estacion (ubicacion, aforo) values ('ONE PENN''S WAY', 5);
insert into estacion (ubicacion, aforo) values ('MAC N9301-041', 6);
insert into estacion (ubicacion, aforo) values ('Av Alfonso IX, 7', 7);
insert into estacion (ubicacion, aforo) values ('720 HIGHWAY 15 SOUTH', 8);
insert into estacion (ubicacion, aforo) values ('Hamngatan 2', 9);
insert into estacion (ubicacion, aforo) values ('3RD FLOOR', 10);
insert into estacion (ubicacion, aforo) values ('320 1ST STREET', 11);
insert into estacion (ubicacion, aforo) values ('Bahnhofstraße 23', 12);
insert into estacion (ubicacion, aforo) values ('Altenburger Straße 13', 13);
insert into estacion (ubicacion, aforo) values ('PIAZZA FILIPPO MEDA 4', 14);
insert into estacion (ubicacion, aforo) values ('1200 E. WARRENVILLE RD', 15);
insert into estacion (ubicacion, aforo) values ('PO BOX 7009', 16);
insert into estacion (ubicacion, aforo) values ('ul. Piłsudskiego 36', 17);
insert into estacion (ubicacion, aforo) values ('16 BOULEVARD DES ITALIENS', 18);
insert into estacion (ubicacion, aforo) values ('Balasta dambis 15', 19);
insert into estacion (ubicacion, aforo) values ('Heinemannstraße 15', 20);
insert into estacion (ubicacion, aforo) values ('4140 EAST STATE STREET', 21);
insert into estacion (ubicacion, aforo) values ('Tilžės g. 149', 22);
insert into estacion (ubicacion, aforo) values ('8001 VILLA PARK DRIVE', 23);
insert into estacion (ubicacion, aforo) values ('111 S. CASAVER', 24);
insert into estacion (ubicacion, aforo) values ('110 S FERRALL STREET', 25);
insert into estacion (ubicacion, aforo) values ('MAC N9301-041', 26);
insert into estacion (ubicacion, aforo) values ('12 PLACE DES ETATS UNIS', 27);
insert into estacion (ubicacion, aforo) values ('7800 E IMPERIAL HWY', 28);
insert into estacion (ubicacion, aforo) values ('Nieheimer Straße 14', 29);
insert into estacion (ubicacion, aforo) values ('1200 E. WARRENVILLE ROAD', 30);
